### ISSUE TITLE
Design rough user flow for UI benefits screener

### ISSUE THREAD

**Issue by mkhandekar** [cagov/benefits-screener#13]
### User story
As a designer/researcher, I need to map out a sequential user flow for the benefits screener, so that...
1. I can check with stakeholders whether my interpretation is correct, 
2. I can coordinate with the engineering team what should be built, and
3. EDD makes it easier for potential applicants to understand if and when they will be able to apply and receive UI benefits.

### Acceptance criteria
- [x] Initial, rough documentation of user flow completed (in Mural or similar, is great). [See here](https://www.lucidchart.com/documents/edit/933c2728-b8da-4eeb-afb7-6b7eab4843a1/uYRPuMkWkyJc?beaconFlowId=CCEF23D17F3A5EEA#?folder_id=home&browser=icon)
- [x] User flow is vetted and approved by stakeholders
- [x] User flow is reviewed by engineering and their biggest questions about implementation has been answered 

### Timeline
-  We're going to aim for Monday 4/13 - Wednesday 4/15 EOD

### Out of scope
- Finalized, plain language content (this will be tracked in #x)

**Comment by nguyen-tina** [comment]
[Here's the link for a rough draft of the user flow](https://www.lucidchart.com/documents/edit/933c2728-b8da-4eeb-afb7-6b7eab4843a1/uYRPuMkWkyJc?beaconFlowId=CCEF23D17F3A5EEA#?folder_id=home&browser=icon) (link also shared above).

**Comment by mkhandekar** [comment]
Closing this as we've moved on to designed screens #14 , and also had them approved! 🎉
