### ISSUE TITLE
Write content for UI application guide

### ISSUE THREAD

**Issue by mkhandekar** [cagov/benefits-screener#15]
### User story
As a designer/researcher, I need to write policy-compliant, plain-language at 6th grade level, trauma-informed content, so that...
1. potential applicants can understand if and when they will be able to apply and receive UI benefits, and 
2. the screener is design and built to match current EDD constraints and needs 

### Acceptance criteria
- [x] Content must be at or below 6th grade reading level (using [Hemmingway App](http://www.hemingwayapp.com/))
- [x] Content for each screen is drafted
- [x] Content for each screen is reviewed by:
  - [x] stakeholders, including EDD policy SMEs
  - [x] content strategy SMEs, such as Corey Mahoney (who drove the [Content Style Guide for the CA Covid-19 website](https://docs.google.com/document/d/1txYjL0T2Qmi6Bn7UMtRyECNGbJpOzVQ5ALtqrVTOPOI/edit)) and potentially Nava content strategy teammates
- [x] Content for each screen is finalized
- [x] Content for each screen is documented with implementation notes for engineering team

### Timeline
-  We're going to aim for Wednesday 4/22 - Friday 4/24

### Out of scope
- Content outside of the screener itself (what is written on the Alpha Covid-19 site, UI Online, etc)

**Comment by mthong** [comment]
@mkhandekar @nguyen-tina In addition to the Content Style Guide linked in the issue description, I just learned from @abquirarte that they've developed a "[Crisis Standard](https://github.com/cagov/covid19/wiki/Crisis-standard)" to maintain the quality of content on the state covid-19 website. In particular, item 3 in the standard reminded me of a goal that Kalvin and Tina already discussed today -- ensuring that the information and language is the same or similar across agencies, and does not conflict.

**Comment by abquirarte** [comment]
Lots of documentation that we are still creating or working on merging 😄 
Here is a more complete style guide that we started documenting in Alpha: https://handbook.alpha.ca.gov/en/latest/content/

**Comment by mthong** [comment]
@mkhandekar @nguyen-tina Flagging the guidance captured in Issue #25 on paper forms (discussed on Friday 4/17 with Dana and Eric), which will ned to be reflected in the "how to apply" content.

**Comment by mthong** [comment]
@mkhandekar @nguyen-tina Also flagging question #24 (What are the requirements for a clean clean?) that was recently updated for you to cross-check with the content you're writing.

**Comment by mkhandekar** [comment]
@mthong You helping with these questions has been so helpful!

Here's the document where we've been writing and reviewing all the content for this page. 

🔒 [CA UI application guidance - content](https://docs.google.com/document/d/1HQDkapLJ7VxvCJxmbk4uGrHxHjNORjDiDi-ms_kY91Q/)

Next steps are to incorporate PAB's 2nd round of review (part of which will be a 2nd round of UI SME feedback as well).
