### ISSUE TITLE
Setup support for multiple languages

### ISSUE THREAD

**Issue by sharonwarner** [cagov/benefits-screener#18]
I've previously used i18n to accommodate multiple languages, and it worked well. For now, we're only supporting English, but we'd like to set the repo up so we can easily add more languages in the future. 

- [x] Setup i18n (or other equivalent library)
- [x] Move "Hello World" text to a 'copy' file

**Comment by kalvinwang** [comment]
Completed in https://github.com/cagov/benefits-screener/pull/30
