### ISSUE TITLE
Determine what header/footer we should use

### ISSUE THREAD

**Issue by sharonwarner** [cagov/benefits-screener#19]
The headers and footers differ between alpha.ca.gov, covid19.ca.gov, and edd.ca.gov. We need to decide which header and footer we should use for the benefits screener.

**Comment by danachis** [comment]
I'd like people to see this as a front door to their EDD interactions. What will it take to tie it to the EDD navigation? What does the front (top?) of the flow chart look like?

**Comment by mkhandekar** [comment]
We should use exactly EDD's header and footer.
