### ISSUE TITLE
Determine favicon, site title, and site description

### ISSUE THREAD

**Issue by sharonwarner** [cagov/benefits-screener#20]
covid19.ca.gov, edd.ca.gov, and alpha.ca.gov all use different favicons. We need to determine which to use for the benefits scanner. We also need to choose a site title and site description.

**Comment by danachis** [comment]
I wonder if it won't be clear what all these things should be when we see a draft of the site.

**Comment by mkhandekar** [comment]
Let's use EDD's favicon

**Title:** Guide to applying for unemployment benefits in California
**Description (also the content in the header):** Learn what type of benefits you qualify for and how to apply for them. If you lost your job or had your hours reduced, and meet eligibility requirements, you may be eligible to receive Unemployment Insurance (UI) benefits from California’s Employment Development Department (EDD).
