### ISSUE TITLE
Will paper applications (for mail and fax submission) be updated for PUA-eligible applicants?

### ISSUE THREAD

**Issue by mthong** [cagov/benefits-screener#25]
We are seeking confirmation from EDD that a paper application is not going to be an option for PUA applicants. 

The current plan for the how-to guide is: 
* Include information on other relevant channels (phone/mail/fax) BUT
* Strongly direct people to apply online because it significantly reduces EDD manual workload, and also takes longer for applicant to get processed (i.e. get money)

History from [Slack thread](https://nava.slack.com/archives/C0118STES6P/p1586810061189600)

**Other notes:** 
* EDD already says this on its website. "UI Online is the fastest and most convenient way to file your UI claim." 
* Per Dana, estimate of channel share is 70% UIO, 20% phone, 10% paper

**Comment by danachis** [comment]
Confirmed: There is no plan to update the paper form for PUA. 
People will still be able to use the paper form to apply for regular UI.

**Comment by mkhandekar** [comment]
Follow up: There's no paper form for PUA. But what about the other programs -- Pandemic Emergency Unemployment Compensation (P-EUC), and the Federal Pandemic Unemployment Compensation (FPUC).

**Comment by danachis** [comment]
Like UIOnline, all of the programs will be handled through the same process, and there is no plan to change the paper forms to include any of the programs that are not already in them in this space-time continuum.

**Comment by mkhandekar** [comment]
Draft for content related to this ticket.

![Screenshot 2020-04-20 09 50 59](https://user-images.githubusercontent.com/1598889/79765607-72509d80-82ec-11ea-8655-51135209e82a.png)

**Comment by danachis** [comment]
The way we should be thinking about this is that CA EDD is trying to do a good thing: NOT force applicants to learn what all the different programs are, but instead, just supply data about their work situation, and EDD will figure out the rest. 

Consider taking off the last sentence. What you have up to that point is enough.

**Comment by mkhandekar** [comment]
Yes, removed the last sentence.
