### ISSUE TITLE
How many concurrent users should we prepare for?

### ISSUE THREAD

**Issue by sharonwarner** [cagov/benefits-screener#26]

**Comment by idealisms** [comment]
That's a good question. Maybe try to estimate load based on these application numbers?
https://edd.ca.gov/newsroom.htm

Assume a certain factor more than the people who apply are going to be reading the screener pages.

**Comment by idealisms** [comment]
Oh, better idea: You should have access to analytics for the other static pages. You can base an estimate on that.

**Comment by idealisms** [comment]
It looks like during the busiest week (Mar 16-Mar 20), there were up to 100k users per hour on edd.ca.gov with an average session duration of 4min. 100000*4/60/60 = ~111 concurrent users. I think that's a pretty safe upper bound as there will likely be less traffic than during that week.

**Comment by sharonwarner** [comment]
Awesome, thanks for the info!
