### ISSUE TITLE
Decide if any MVP content is needed to help users who arrive from Spanish version of EDD site

### ISSUE THREAD

**Issue by mthong** [cagov/benefits-screener#41]
**EDD site experience for users who prefer to read in other languages than English:**
* EDD website has a Google translate toggle in the footer, along with a disclaimer that states:
> "The web pages currently in English on the EDD website are the official and accurate source for the program information and services the EDD provides...If any questions arise related to the information contained in the translated website, please refer to the English version." 

* At the same time we see that most content for Unemployment is manually translated into Spanish, such as these pages on [Filing a UI Claim](https://edd.ca.gov/Unemployment/Filing_a_Claim.htm), [Pandemic Unemployment Assistance](https://edd.ca.gov/about_edd/coronavirus-2019/pandemic-unemployment-assistance-espanol.htm), and the [UI Online introduction](https://edd.ca.gov/Unemployment/UI_Online_Espanol.htm)

**How-to experience for users who prefer other languages:**
* MVP will not have any support for other languages
* Users may arrive from EDD site, either a manually translated Spanish page or a Google-translated page in many possible languages. 
* Every page of UI content as well as the UIO user flow appears to be manually translated into Spanish. 
* It could be jarring for users to suddenly go from a translated page to English.

**Comment by ehysen** [comment]
If we can support it from a tech perspective, we can turn around manual Spanish translations in 24 hours. But would first discuss with PAB during the meeting tomorrow and get their perspective on priority.

**Comment by mthong** [comment]
@mkhandekar I drew up a [rough diagram](https://docs.google.com/presentation/d/1vVAgkDUN7hTph81k47lFfhXdrqIrBq1b1iwJI6k9sF0/edit?usp=sharing) of the current and desired user flow for Spanish readers that attempts to explain why we might want to add a link to return them to the Spanish UIO app even in our English-only MVP.

**Comment by mthong** [comment]
At our 4/22/2020 meeting with EDD Public Affairs, we agreed on the following approach:
* For the MVP launch on Monday 4/27, we will not have a Spanish language version of the how-to guide. 
* For the MVP launch on Monday 4/27, EDD will not update their manually translated Spanish pages to link to the how-to guide. 
* As soon as we have final content, we can start the process of getting it translated, with the goal of making the Spanish version of the how-to guide available as soon as possible after the Monday 4/27 launch. 

@ehysen, what translation resource were you thinking we'd tap into for the 24-hour turnaround on the translation next week? 

EDD PAB asked us if we would use their translation partners, and said they would investigate how long the turnaround time would be (between 1-5 days). There could be an advantage to using their translators, for consistency in UI-specific terminology.
