### ISSUE TITLE
Get EDD approval of URL

### ISSUE THREAD

**Issue by mthong** [cagov/benefits-screener#43]
We need to:
* Internally among ODI/Nava agree on what URL we will propose.
* Propose it to EDD at our Wed 4/22 meeting and either get their agreement on the spot or give them a timeline for a decision (suggest Thur 4/23 10am PT). 

The URL is related to, but separate from, the name for the tool. 

As of 4/21, the URL that CDT has created for us is screener.edd.ca.gov, but we have pivoted away from the screener name. 

Ideas:
* unemployment.edd.ca.gov/how-to-apply
* apply.edd.ca.gov/how-to-guide
* apply.edd.ca.gov/unemployment
* apply4ui.edd.ca.gov/how-to
* apply-ui.edd.ca.gov/how-to 
* ui-navigator.edd.ca.gov/how-to
* navigator.edd.ca.gov/unemployment

Comments:
* EDD may resist URLs such as apply.edd.ca.gov that don't clearly limit scope to UI (because they have other programs)
* We want it to be memorable, something the Governor could say aloud in a press briefing
* Ideally we want it to be general enough that we could expand the use of the site for future work (not just the guide)

**Comment by danachis** [comment]
The convention on the site seems to be 
edd.ca.gov/[topic] 

For example: 
- edd.ca.gov/claims.htm
- edd.ca.gov/about_edd/coronavirus-2019.htm
- edd.ca.gov/Unemployment/Filing_a_Claim.htm

This is true of Alpha's covid sites, too. 
- covid19.ca.gov/taxes/
- covid19.ca.gov/education/#top
Etc. 

Alpha's sites look like this: 
- alpha.ca.gov/apply-for-unemployment-insurance/
- alpha.ca.gov/find-shelters-near-you/?q=94133

so we might think about something like: 
edd.ca.gov/ui-how-to
edd.ca.gov/navigate-ui
edd.ca.gov/navigate-unemployment
edd.ca.gov/navigateUI


We also need to figure out where it should go in the flow. Here's a [link to MIRO](https://miro.com/app/board/o9J_kzge8rE=/?moveToWidget=3074457347689180083&cot=13) showing where the how-to guide could live.

**Comment by danachis** [comment]
The state has [domain standard](https://cdt.ca.gov/wp-content/uploads/2017/05/SIMM-40A-Internet-Domain-Instructions.pdf).

**Comment by mthong** [comment]
@danachis I think it makes sense to consider using the standard EDD domain, edd.ca.gov. I checked with @sharonwarner and she said this was possible even though our pages will technically live somewhere other than the EDD website.

I do notice that EDD apps that are separate from the website have other URLs, e.g. 
- [For Ask EDD: askedd.edd.ca.gov](https://askedd.edd.ca.gov)
- [For UIO: portal.edd.ca.gov](https://portal.edd.ca.gov/)

So a separate domain may still make sense, especially if we were to end up building out a suite of other related tools that stand alongside the existing EDD main website (this is something @ehysen suggested on 4/20).

**Comment by mthong** [comment]
How about **edd.ca.gov/unemployment/guide** or **edd.ca.gov/unemployment/start**? 

Pros: 
- looks like it lives within the EDD website and specifically within their unemployment content family. 
- appropriate to what the guide is for now at least - a whole new URL for one page of content may be a bit much! 

Cons: 
- not short, catchy or memorable
- no one will be able to speak these URLs out loud, making us more reliant on EDD linking to them in their communications and website

**Comment by mthong** [comment]
URLs from other states (none of these are great) 
https://www.mass.gov/how-to/apply-for-pandemic-unemployment-assistance
https://labor.ny.gov/unemploymentassistance.shtm
https://labor.ny.gov/ui/cares-act.shtm
https://esd.wa.gov/unemployment

**Comment by mthong** [comment]
Here are some constraints I propose limit our options and help us converge:
* avoid the use of "ui" because it seems like users don't necessarily know what those initials stand for
* avoid the use of dashes because it makes it hard to share verbally and easy to type incorrectly
* avoid caps because it also over-complicates things and results in typos

**Comment by mkhandekar** [comment]
+1 to not having the acronym ui in the URL, we heard some confusion from users yesterday, we should keep in mind that most people applying would have never applied for these benefits before.

**edd.ca.gov/unemployment/start** has a good ring to me, and also matches the sense we got from users yesterday. After going through the various sections on the page, they mentioned that "this is more than just info about apply, it's more of a general overview at everything you might do or want to be aware of".  While we're going to talk to more users this week, I think this URL is a good descriptor of what the page contains.

My other +1 would be for edd.ca.gov/navigate-unemployment or edd.ca.gov/startunemployment (which is not very easy on the eyes, but removes the dash).

**Comment by danachis** [comment]
Updated the possible URLs in the [screen flow diagram I created in Miro](https://miro.com/app/board/o9J_kzge8rE=/?moveToWidget=3074457347689180083&cot=13) https://miro.com/app/board/o9J_kzge8rE=/?moveToWidget=3074457347689180083&cot=13

**Comment by danachis** [comment]
PDF of the EDD-PUA screen flow [EDD-PUA_screen-flow_22Apr2020.pdf](https://github.com/cagov/benefits-screener/files/4517559/EDD-PUA_screen-flow_22Apr2020.pdf)

**Comment by mthong** [comment]
We have decided on unemployment.edd.ca.gov/guide
